#!/usr/bin/env bash

# HW
alias keys='xev -event mouse -event keyboard'
alias webcam='ffmpeg -f v4l2 -input_format mjpeg -video_size 1920x1080 -i /dev/video0 -vf format=yuyv422 -f v4l2 /dev/video2'
alias webcamb='ffmpeg -f v4l2 -input_format mjpeg -video_size 160x120 -i /dev/video0 -vf format=yuyv422 -f v4l2 /dev/video2'

# Clipboard
alias copy='xclip -sel clip'
alias paste='xclip -o'
alias gp="openssl rand -base64 32 | copy" # Gen password

# Mailspring
alias fms='rm -rf $XDG_CONFIG_HOME/Mailspring/*[Cc]ache*'
