Net/CursorBlinkTime 1000
Net/CursorBlink 1
Net/SoundThemeName "ocean"
Net/ThemeName "Breeze-Dark"
Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 2
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 48
Gtk/CursorThemeName "gunsights"
Net/IconThemeName "breeze-dark"
Gtk/FontName "Nunito Sans, Medium 12"

